apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-ci-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circle-ci-app
  template:
    metadata:
      labels:
        app: circle-ci-app
    spec:
      containers:
      - name: circle-ci-app
        image: us-central1-docker.pkg.dev/mlops-466014/circle-ci-app/circle-ci-app:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: circle-ci-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer