version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with GCP
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build and Push Docker Image
          command: |
              command: |
                if [ -z "$GOOGLE_PROJECT_ID" ]; then
              echo "ERROR: GOOGLE_PROJECT_ID environment variable is not set."
              exit 1
                fi
              IMAGE_TAG="us-central1-docker.pkg.dev/${GOOGLE_PROJECT_ID}/circle-ci-app/circle-ci-app:latest"
              echo "Building and pushing image: ${IMAGE_TAG}"
              docker build -t "${IMAGE_TAG}" .
              docker push "${IMAGE_TAG}"

  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticated into GCP
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      
      - run:
          name: Configure GKE
          command: |
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
              kubectl apply -f kubernetes-deployment.yaml

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image